services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Raj4@sql
      DB_NAME: marketplace

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Raj4@sql
      MYSQL_DATABASE: marketplace
      MYSQL_USER: root
      MYSQL_PASSWORD: Raj4@sql
    command: --default-authentication-plugin=mysql_native_password
